source 'http://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'capybara'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'rubocop'
gem 'faker'
gem 'cpf_faker'
gem 'httparty'
gem 'ostruct'
gem 'openssl'
gem 'ruby-debug-ide'
gem 'rdebug'
gem 'pg'